services:
  wallbox-monitor:
    container_name: wallbox-monitor
    build:
      context: .
      dockerfile: Containerfile 
    image: localhost/wallbox-monitor:latest
    ports:
      - "2114:2114"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ~/app-data/wallbox-monitor:/app/log:Z
    userns_mode: keep-id
    restart: unless-stopped

    # Automated native Podman/Docker log rotation for standard terminal streams (fmt.Printf)
    logging:
      driver: k8s-file
      options:
        max-size: "10mb"
        max-file: "3"
