---
- hosts: all
  become: true

  # Define your centralized configuration variables here
  vars:
    wallbox_data_dir: "/mnt/cluster-volumes/wallbox-monitor"
    listen_port: "2114"
    timezone: "Europe/Berlin"

  pre_tasks:
    - name: Update package cache and install updates
      ansible.builtin.apt:
        update_cache: yes
        upgrade: full
        cache_valid_time: 43200
        force_apt_get: True
      when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']

  tasks:
    - name: Skip if OS not supported
      ansible.builtin.meta: end_host
      when: ansible_facts['distribution'] not in ['Debian', 'Ubuntu']

    - ansible.builtin.import_tasks: install-app.yml
    #- ansible.builtin.import_tasks: install-container.yml
