package variables

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// App information
const (
	AppName    = "wallbox-monitor"
	AppVersion = "1.0.1"
)

// Configuration constants
const (
	FetchIntervalInMilliSeconds                              = 5000
	RetryIntervalInMilliSeconds                              = 250
	MaxRetriesToFetchDataUntilInvalid                        = 60
	StartDelayInMilliSeconds                                 = 2000
	OutputRefreshIntervalInMilliSeconds                      = 5000 // Also used for JSON file updates
	HomeAssistantUpdateIntervalInOutputRefreshLoopIterations = 5    // 5 * OutputRefreshIntervalInOutputRefreshLoopIterations (e.g. 2000) = 10.000ms (10s)
	HomeAssistantLogApiCallResult200                         = true
	JsonFileNameSuffixAfterAutogeneratedTimePrefix           = "-wallbox.json"
)

// Configuration defaults that may be overridden by environment variables
var (
	WallboxIp      = "192.168.30.40"
	WallboxPort    = "80"
	PrometheusPort = "2114"
)

// Runtime configuration
var (
	ClearLoopOutput          = true
	OutputJson               = true
	WriteJsonToFile          = true
	EnablePrometheus         = true
	EnableHomeAssistant      = false
	JsonFileLocation         string
	ForceUpdateHomeAssistant bool
)

// JSON DATA
type JsonData struct {
	Date     string    `json:"Date"`
	Time     string    `json:"Time"`
	TimeZone string    `json:"TimeZone"`
	Car      int       `json:"Car"`
	Amp      int       `json:"Amp"`
	Nrg      []float64 `json:"Nrg"`
	Wh       float64   `json:"Wh"`
	Dws      float64   `json:"Dws"`
	Psm      int       `json:"Psm"`
	Frc      int       `json:"Frc"`
	Tma      []float64 `json:"Tma"`
	Alw      bool      `json:"Alw"`
}

type WallboxApiCall struct {
	Name        string
	Enabled     bool
	Filter      string
	Description string
}

var WallboxApiCalls = []WallboxApiCall{
	{Name: "car", Enabled: true, Filter: "car", Description: "Car state (unknown, idle, charging, wait car, finished)"},
	{Name: "amp", Enabled: true, Filter: "amp", Description: "Requested current limit in Amperes"},
	{Name: "nrg", Enabled: true, Filter: "nrg", Description: "Electrical measurement array: voltage, current, total power"},
	{Name: "wh", Enabled: true, Filter: "wh", Description: "Life-to-date total charged energy in Watt-hours"},
	{Name: "dws", Enabled: true, Filter: "dws", Description: "Energy delivered during current charging session in Deciwatt-seconds"},
	{Name: "psm", Enabled: true, Filter: "psm", Description: "Current supply phase mode"},
	{Name: "frc", Enabled: true, Filter: "frc", Description: "Charge control override state"},
	{Name: "tm", Enabled: true, Filter: "tma", Description: "Device internal microprocessor temperatures"},
	{Name: "alw", Enabled: true, Filter: "alw", Description: "Clear-to-charge status flag"},
}

func EnabledWallboxFilters() []string {
	filters := make([]string, 0, len(WallboxApiCalls))
	for _, apiCall := range WallboxApiCalls {
		if apiCall.Enabled {
			filters = append(filters, apiCall.Filter)
		}
	}
	return filters
}

type CalcData struct {
	Id          string
	Query       string
	Output      string
	DateNow     string
	TimeNow     string
	TimeZoneNow string
}

var CalcValues = []CalcData{
	{Id: "TotalHouse", Query: "float32", Output: "", DateNow: "", TimeNow: "", TimeZoneNow: ""},
}

// HomeAssistant configuration
var (
	UrlHomeAssistant              = "http://192.168.1.8:8123"
	TokenHomeAssistant            string
	ApiBoolWallboxChargeAllowed   = "/api/states/input_boolean.wallbox_charge_allowed"
	ApiIntWallboxAmpLimit         = "/api/states/input_number.wallbox_amp_limit_amps"
	ApiIntWallboxPowerW           = "/api/states/input_number.wallbox_power_w"
	ApiIntWallboxTotalEnergyWh    = "/api/states/input_number.wallbox_total_energy_wh"
	ApiIntWallboxSessionEnergyDws = "/api/states/input_number.wallbox_session_energy_dws"
	ApiIntWallboxPhaseMode        = "/api/states/input_number.wallbox_phase_mode"
	ApiIntWallboxOverrideState    = "/api/states/input_number.wallbox_override_state"
)

// System information
var (
	GOOS   = runtime.GOOS
	GOARCH = runtime.GOARCH
)

func init() {
	userHome, _ := os.UserHomeDir()
	JsonFileLocation = filepath.Join(userHome, "wallbox-monitor")

	if env := os.Getenv("WALLBOX_IP"); env != "" {
		WallboxIp = env
	}
	if env := os.Getenv("WALLBOX_PORT"); env != "" {
		WallboxPort = env
	}
	if env := os.Getenv("PROMETHEUS_PORT"); env != "" {
		PrometheusPort = env
	}
	if env := os.Getenv("JSON_FILE_LOCATION"); env != "" {
		JsonFileLocation = env
	}
	if env := os.Getenv("ENABLE_PROMETHEUS"); env != "" {
		EnablePrometheus = parseBoolEnv(env, EnablePrometheus)
	}
	if env := os.Getenv("ENABLE_HOME_ASSISTANT"); env != "" {
		EnableHomeAssistant = parseBoolEnv(env, EnableHomeAssistant)
	}
	if env := os.Getenv("WRITE_JSON_TO_FILE"); env != "" {
		WriteJsonToFile = parseBoolEnv(env, WriteJsonToFile)
	}
	if env := os.Getenv("OUTPUT_JSON"); env != "" {
		OutputJson = parseBoolEnv(env, OutputJson)
	}
	if env := os.Getenv("HOME_ASSISTANT_URL"); env != "" {
		UrlHomeAssistant = env
	}
	TokenHomeAssistant = os.Getenv("HOME_ASSISTANT_TOKEN")
}

func parseBoolEnv(value string, defaultValue bool) bool {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "1", "true", "yes", "on":
		return true
	case "0", "false", "no", "off":
		return false
	default:
		return defaultValue
	}
}
