package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
	"wallbox-monitor/generalUtils"
	"wallbox-monitor/homeassistantApi"
	"wallbox-monitor/prometheus"
	"wallbox-monitor/variables"
	"wallbox-monitor/wallboxApi"
)

func main() {
	fmt.Printf("%s %s (%s/%s)\n\n", variables.AppName, variables.AppVersion, variables.GOOS, variables.GOARCH)

	time.Sleep(time.Millisecond * time.Duration(variables.StartDelayInMilliSeconds))
	if variables.EnablePrometheus {
		go prometheus.StartServer(variables.PrometheusPort)
	}

	fmt.Println("Waiting for wallbox data...")
	status, err := fetchWallboxStatus()
	for err != nil {
		fmt.Println("Wallbox fetch failed:", err)
		time.Sleep(time.Millisecond * time.Duration(variables.RetryIntervalInMilliSeconds))
		status, err = fetchWallboxStatus()
	}
	fmt.Printf("\n =========================================== \n\n")

	lc := 0
	variables.ForceUpdateHomeAssistant = true
	for {
		lc++

		if variables.ClearLoopOutput {
			clearScreen()
		}

		status, err = fetchWallboxStatus()
		if err != nil {
			fmt.Println("Wallbox fetch failed:", err)
			time.Sleep(time.Millisecond * time.Duration(variables.RetryIntervalInMilliSeconds))
			continue
		}

		dateNow, timeNow, timeZone, _, _ := generalUtils.GetDateAndTime()
		jsonString := generalUtils.CreateJsonStringFromWallbox(dateNow, timeNow, timeZone, status)

		if variables.EnablePrometheus {
			prometheus.UpdateMetrics(status)
		}

		if variables.EnableHomeAssistant && (variables.ForceUpdateHomeAssistant || lc >= variables.HomeAssistantUpdateIntervalInOutputRefreshLoopIterations) {
			updateHomeAssistant(status)
			variables.ForceUpdateHomeAssistant = false
			lc = 0
		}

		if variables.WriteJsonToFile {
			_, _, _, month, year := generalUtils.GetDateAndTime()
			jsonFile := filepath.Join(variables.JsonFileLocation,
				fmt.Sprintf("%s-%s%s", year, month,
					variables.JsonFileNameSuffixAfterAutogeneratedTimePrefix))
			if err := generalUtils.WriteJsonToFile(jsonString, jsonFile); err != nil {
				fmt.Println("Failed to write JSON file:", err)
			}
		}

		if variables.OutputJson {
			displayJsonOutput(jsonString)
		} else {
			displayTextOutput(status)
		}

		fmt.Println()
		time.Sleep(time.Millisecond * time.Duration(variables.OutputRefreshIntervalInMilliSeconds))
	}
}

func fetchWallboxStatus() (*wallboxApi.Status, error) {
	filters := strings.Join(variables.EnabledWallboxFilters(), ",")
	return wallboxApi.FetchStatus(variables.WallboxIp, variables.WallboxPort, filters)
}

func clearScreen() {
	var cmd *exec.Cmd
	switch variables.GOOS {
	case "darwin", "linux":
		cmd = exec.Command("clear")
	case "windows":
		cmd = exec.Command("cmd", "/c", "cls")
	default:
		return
	}
	cmd.Stdout = os.Stdout
	cmd.Run()
}

func updateHomeAssistant(status *wallboxApi.Status) {
	state := map[bool]string{true: "on", false: "off"}
	chargeAllowed := bool(status.Alw)

	homeassistantApi.CallHomeAssisatantApiSet(variables.ApiBoolWallboxChargeAllowed,
		generalUtils.CreateJSONReaderKeyValue("state", state[chargeAllowed]))

	power := 0.0
	if len(status.Nrg) > 2 {
		power = status.Nrg[2]
	}

	homeassistantApi.CallHomeAssisatantApiSet(variables.ApiIntWallboxAmpLimit,
		generalUtils.CreateJSONReaderKeyValue("state", fmt.Sprintf("%d", status.Amp)))
	homeassistantApi.CallHomeAssisatantApiSet(variables.ApiIntWallboxPowerW,
		generalUtils.CreateJSONReaderKeyValue("state", fmt.Sprintf("%.0f", power)))
	homeassistantApi.CallHomeAssisatantApiSet(variables.ApiIntWallboxTotalEnergyWh,
		generalUtils.CreateJSONReaderKeyValue("state", fmt.Sprintf("%.0f", status.Wh)))
	homeassistantApi.CallHomeAssisatantApiSet(variables.ApiIntWallboxSessionEnergyDws,
		generalUtils.CreateJSONReaderKeyValue("state", fmt.Sprintf("%.0f", status.Dws)))
	homeassistantApi.CallHomeAssisatantApiSet(variables.ApiIntWallboxPhaseMode,
		generalUtils.CreateJSONReaderKeyValue("state", fmt.Sprintf("%d", status.Psm)))
	homeassistantApi.CallHomeAssisatantApiSet(variables.ApiIntWallboxOverrideState,
		generalUtils.CreateJSONReaderKeyValue("state", fmt.Sprintf("%d", status.Frc)))
}

func displayJsonOutput(jsonString []byte) {
	var prettyJSON bytes.Buffer
	if err := json.Indent(&prettyJSON, jsonString, "", "    "); err != nil {
		fmt.Println("Error:", err)
		return
	}
	fmt.Println(prettyJSON.String())
}

func displayTextOutput(status *wallboxApi.Status) {
	timeStamp := time.Now().String()
	fmt.Printf("%s %s %s (%s)\n", time.Now().Format("2006/01/02"), time.Now().Format("15:04:05"), time.Now().Location(), timeStamp)
	fmt.Printf("Car status: %d\n", status.Car)
	fmt.Printf("Amp limit: %d A\n", status.Amp)
	if len(status.Nrg) >= 3 {
		fmt.Printf("Voltage: %.2f V\n", status.Nrg[0])
		fmt.Printf("Current: %.2f A\n", status.Nrg[1])
		fmt.Printf("Power: %.2f W\n", status.Nrg[2])
	}
	fmt.Printf("Total energy: %.2f Wh\n", status.Wh)
	fmt.Printf("Session energy: %.2f dWs\n", status.Dws)
	fmt.Printf("Phase mode: %d\n", status.Psm)
	fmt.Printf("Override state: %d\n", status.Frc)
	for idx, tma := range status.Tma {
		fmt.Printf("Temp sensor %d: %.2f °C\n", idx, tma)
	}
	fmt.Printf("Charge allowed: %t\n", bool(status.Alw))
}
